schema-version = 1
release-version = "5.0.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.50.0"
vendor = "bottlerocket"

[vendor.cast]
registry = "028075177508.dkr.ecr.eu-central-1.amazonaws.com"
[[kit]]
name = "bottlerocket-core-kit" # Name of your ECR repo
version = "4.0.1" # your version tag you want to test
vendor = "cast"
